#------------定义ns----------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rabbit
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - image: bitnami/rabbitmq:latest
          imagePullPolicy: IfNotPresent
          name: rabbit
          ports:
            - containerPort: 15672
              name: rabbit15672
              protocol: TCP
            - containerPort: 5672
              name: rabbit5672
              protocol: TCP
          resources: { }
          volumeMounts:
            - mountPath: /bitnami
              name: rabbit-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - name: rabbit-persistent-storage
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: dev
spec:
  ports:
    - name: rabbit15672
      nodePort: 31672
      port: 15672
      protocol: TCP
      targetPort: 15672
    - name: rabbit5672
      nodePort: 32672
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbit
  type: NodePort